In [ ]:
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

In [165]:
import numpy as np
import pandas as pd
import csv, math

%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats 

In [185]:
demo = pd.read_csv('data/NolongCOVID_studypop_plan.csv')

In [173]:
demo

PatientId              Class
0      293272|CHN|Intergy.HCN           Medicaid
1      80167|BAHC|Intergy.HCN  Private Insurance
2      80167|BAHC|Intergy.HCN           Medicare
3      81486|BAHC|Intergy.HCN           Medicaid
4      81486|BAHC|Intergy.HCN  Private Insurance
...                       ...                ...
35602   1704|PKMQ|Intergy.HCN           Medicaid
35603  41927|PKMQ|Intergy.HCN           Medicare
35604  13052|PKMQ|Intergy.HCN           Medicaid
35605  50341|PKMQ|Intergy.HCN           Medicaid
35606  43865|PKMQ|Intergy.HCN           Medicaid

[35607 rows x 2 columns]

In [186]:
## Age
demo.Class.value_counts() 
a0 = len(demo[demo['Class']=='Self'])/len(demo)
a1 = len(demo[demo['Class']=='Medicaid'])/len(demo)
a2 = len(demo[demo['Class']=='Medicare'])/len(demo)
a3 = (len(demo[demo['Class']=='Other']) + len(demo[demo['Class']=='Private Insurance']))/len(demo)
a4 = 1 - (a0+a1+a2+a3)
print([100*a0, 100*a1, 100*a2, 100*a3, 100*a4])

[0.8779117406063445, 24.86831323890905, 7.807561746459089, 66.44621327402552, 0.0]


In [151]:
a1 = len(demo[demo['Age']<18])
a2 = len(demo[demo['Age']<25]) - a1
a3 = len(demo[demo['Age']<35]) - a1 -a2
a4 = len(demo[demo['Age']<45]) - a1 -a2 -a3
a5 = len(demo[demo['Age']<55]) - a1 -a2 -a3 -a4
a6 = len(demo[demo['Age']<65]) - a1 -a2 -a3 -a4 -a5
a7 = len(demo[demo['Age']>65])
a8 = len(demo) - sum(np.array([a1, a2, a3, a4, a5, a6, a7]))
A = np.array([a1, a2, a3, a4, a5, a6, a7, a8])

A_pct = 100*A/sum(A)

In [152]:
A, A_pct

(array([589, 281, 583, 567, 572, 544, 225,   0]),
 array([17.52454627,  8.36060696, 17.34602797, 16.86997917, 17.01874442,
        16.18565903,  6.69443618,  0.        ]))

In [22]:

aa = np.array([15.79, 7.60, 16.18, 16.35, 16.77, 15.30, 6.26, 5.75])


In [88]:
## Gender
demo.Sex.value_counts()

F    24292
M    14193
U       36
        12
Name: Sex, dtype: int64

In [153]:
g1 = len(demo[demo['Sex']=='F'])
g2= len(demo[demo['Sex']=='M'])
g3 = len(demo) - g1 -g2
G = np.array([g1, g2, g3])
             
G_pct = 100*G/sum(G)

In [154]:
G

array([2231, 1129,    1])

In [155]:
G_pct

array([6.63790539e+01, 3.35911931e+01, 2.97530497e-02])

In [156]:
r_w = len(demo[(demo['RaceCode']=='C') & (demo['EthnicityCode']=='N') ])
r_b= len(demo[(demo['RaceCode']=='B')  & (demo['EthnicityCode']=='N')])
r_h= len(demo[demo['EthnicityCode']=='L'])
r_na= len(demo[demo['RaceCode']=='I'])
r_a= len(demo[demo['RaceCode']=='A'])
r_p= len(demo[demo['RaceCode']=='P'])
r_m= len(demo[demo['RaceCode']=='M'])
r_other = r_na + r_a + r_p   + r_m
r_u = len(demo) - sum([r_w , r_b, r_h, r_other])

R = np.array([r_w , r_b, r_h, r_other, r_u])
print(sum(R))
             
R_pct = 100*R/sum(R)

3361


In [157]:
R

array([ 247,  604, 2291,  187,   32])

In [158]:
R_pct

array([ 7.34900327, 17.97084201, 68.16423683,  5.56382029,  0.95209759])

In [46]:
# Eth

g1 = len(demo[demo['EthnicityCode']=='L'])
g2= len(demo[demo['EthnicityCode']=='N'])
g3 = 4091 - g1 -g2
G = np.array([g1, g2, g3])
             
G_pct = 100*G/sum(G)

In [47]:
G

array([2645, 1088,  358])

In [48]:
G_pct

array([64.6541188 , 26.59496456,  8.75091665])

In [159]:
a0 = len(demo[demo['NumberSupported']==0])
a1 = len(demo[demo['NumberSupported']==1])
a2 = len(demo[demo['NumberSupported']==2]) 
a12 = a1 +a2
a3 = len(demo[demo['NumberSupported']==3])
a4 = len(demo[demo['NumberSupported']==4])
a34 = a3+a4
a5m = len(demo[demo['NumberSupported'] > 5]) 

au = len(demo) - (a0 + a12 + a34 + a5m)

A = np.array([a0, a12, a34, a5m, au])
A_pct = 100*A/sum(A)

In [160]:
A

array([ 835, 1142,  910,  185,  289])

In [161]:
A_pct

array([24.84379649, 33.97798274, 27.07527522,  5.50431419,  8.59863136])

In [111]:
22.51+32.51+25.96+5.26+13.76

100.0

In [162]:
a1 = len(demo[demo['PovertyPercent']<=100])
a14 = len(demo[demo['PovertyPercent']<400]) - a1
a4 = len(demo[demo['PovertyPercent']>=400]) 
a0 = len(demo[demo['PovertyPercent']==0]) 
au = len(demo) - (a1 + a14 + a4)

A = np.array([a1, a14, a4, au])
A_pct = 100*A/sum(A)

In [163]:
A

array([2704,  610,   47,    0])

In [164]:
A_pct

array([80.45224636, 18.14936031,  1.39839334,  0.        ])